package javaException;

public class MainClass {
    public static void main(String[] args){

        try{

        }
        finally {
            System.out.println("We are in finally block");
        }
        System.out.println("We are in end main method");
    }
}
